export const restaurants = [
    {
      title: "Gimbap Chonguk",
      menu: [
        { title: "Paradise Gimbab", price: 2000 },
        { title: "Kimchi Gimbab", price: 2500 },
        { title: "Cheese Gimbap", price: 2500 },
        { title: "Tuna Gimbap", price: 3000 },
        { title: "Chily Gimbap", price: 3000 },
        { title: "Beef Gimbap", price: 3000 },
        { title: "Deep Fried pork Gimbap", price: 3000 },
        { title: "Pork Gimbap", price: 3000 },
        { title: "Shrimp Gimbap", price: 3500 },
        { title: "Ramen", price: 2500 },
        { title: "Egg Ramen", price: 3000 },
        { title: "Kimchi Ramen", price: 3000 },
        { title: "Rice cake Ramen", price: 3500 },
        { title: "Cheese Ramen", price: 3500 },
        { title: "Pork dumpling Ramen", price: 3500 },
        { title: "Hangover Ramen", price: 4000 },
        { title: "Spicy seafood Ramen", price: 4000 },
        { title: "Rice cake with spicy red sauce", price: 3000 },
        { title: "Rice cake Ramen spicy sauce", price: 3500 },
        { title: "Spicy stir-fried Rice cake", price: 3500 },
        { title: "Cheese Rice cake Ramen spicy sauce", price: 4000 },
        { title: "Cheese spicy stir-fried Rice cake", price: 4000 },
        { title: "Boiled fish paste soup", price: 2500 },
        { title: "Japanese thick noodle soup", price: 3500 },
        { title: "Japanese thick noodle seafood", price: 4500 },
        { title: "Mixed noodles with spicy red", price: 4500 },
        { title: "Dough noodles with vegetables", price: 4500 },
        { title: "Chopped noodles", price: 4500 },
        { title: "Rice cake soup", price: 4000 },
        { title: "Pork dumpling soup", price: 4500 },
        { title: "Rice cake and pork dumpling soup", price: 4500 },
        { title: "Sticky noodle", price: 4000 },
        { title: "Cold noodies in ice water", price: 4000 },
        { title: "Spicy buckwheat noodle", price: 4000 },
        { title: "Pork dumpling", price: 3500 },
        { title: "Kimchi dumpling", price: 3500 },
        { title: "Boiled dumpling", price: 3500 },
        { title: "Fried dumpling", price: 3500 },
        { title: "Mussel porridge", price: 6500 },
        { title: "Beef and vegetable porridge", price: 6000 },
        { title: "Pumpkin porridge", price: 6000 },
        { title: "Pork with Rice (spicy)", price: 5000 },
        { title: "Marinnated Beef Rice", price: 5500 },
        { title: "Squid with Rice (spicy)", price: 5500 },
        { title: "Stir-fried Rice with veges wrapped with egg", price: 5500 },
        { title: "Mixture of rice, veges, small pieces of beef in metal bowl", price: 4500 },
        { title: "Kimchi with rice pork", price: 4500 },
        { title: "Shrimp fried rice", price: 5500 },
        { title: "Seafood fried rice", price: 5500 },
        { title: "Caviar rice in sizzling hot pot", price: 5000 },
        { title: "Hot pot Rice", price: 5500 },
        { title: "Kimchi soup", price: 5000 },
        { title: "Tuna Kimchi soup", price: 5000 },
        { title: "Soybeen pastesoup", price: 4500 },
        { title: "Soft tofu soup (spicy)", price: 4500 },
        { title: "Hot pot Bulgogi", price: 6000 },
        { title: "Kimchi soup with Blue Cod fish (spicy)", price: 6000 },
        { title: "Sausages stew", price: 6000 },
        { title: "Mixed soup with vegesand beef (spicy)", price: 6000 },
        { title: "Bone-beef soup with noodles", price: 6000 },
        { title: "Beef soup with noodles", price: 6000 },
        { title: "Seafood soup with fish eggs (spicy)", price: 6000 },
        { title: "Rice topped with chicken", price: 5500 },
        { title: "Bowl of Rice", price: 1000 },
        { title: "Fried egg", price: 500 },
        { title: "Large sized deep-fried pork", price: 5500 },
        { title: "Cheese deep-fried pork", price: 6000 },
        { title: "Sweet potato deep-fried pork", price: 6000 },
      ],
    },
    {
      title: "BHC Chicken",
      menu: [
        { title: "Bburinkle Chicken", price: 18000 },
        { title: "Boneless Bburinkle Chicken", price: 20000 },
        { title: "Gold-King Chicken", price: 17000 },
        { title: "Boneless Gold-King Chicken", price: 20000 },
        { title: "Matcho-King Chicken", price: 18000 },
        { title: "Boneless Matcho-King Chicken", price: 20000 },
        { title: "Red-King Chicken", price: 19000 },
        { title: "Boneless Red-King Chicken", price: 20000 },
        { title: "Sunflower Fried Chicken", price: 17000 },
        { title: "Boneless Sunflower Fried Chicken", price: 20000 },
        { title: "Half Sauce & Half Chicken", price: 18000 },
        { title: "Sweet & Sour Sauce Chicken", price: 18000 },
        { title: "Bburinkle Combo", price: 20000 },
        { title: "Gold-King Combo", price: 20000 },
        { title: "Fried Chicken Combo", price: 20000 },
        { title: "Matcho-King Combo", price: 20000 },
        { title: "Bburinkle Wing", price: 20000 },
        { title: "Gold-King Wing", price: 20000 },
        { title: "Fried Chicken Wing", price: 20000 },
        { title: "Matcho-King Wing", price: 20000 },
        { title: "Bburinkle Stick", price: 20000 },
        { title: "Gold-King Stick", price: 20000 },
        { title: "Fried Chicken Stick", price: 20000 },
        { title: "Matcho-King Stick", price: 20000 },
        { title: "Sweet and crunchy cheese boul", price: 5000 },
        { title: "Sweet red bean twist", price: 5000 },
        { title: "Bburing Cheese Boul", price: 6000 },
        { title: "Bburing Potatoes", price: 4500 },
        { title: "Creem Cheese Twist", price: 5500 },
      ],
    },
    {
      title: "Mom's Touch",
      menu: [
        { title: "Tandoori Thigh Burger", price: 5200 },
        { title: "Mala Thigh Burger", price: 5200 },
        { title: "Arrabbiata Cheese Burger", price: 7100 },
        { title: "Incredible Burger", price: 5700 },
        { title: "Shrimp Thigh Flex Burger", price: 7000 },
        { title: "Thigh Flex Burger", price: 7700 },
        { title: "Thigh Burger", price: 4600 },
        { title: "Spicy Thigh Burger", price: 4800 },
        { title: "Jalapeno Thigh Burger", price: 4800 },
        { title: "Deep Cheese Thigh Burger", price: 5100 },
        { title: "White Garlic Thigh Burger", price: 5200 },
        { title: "Unbelievable Burger", price: 5900 },
        { title: "White Garlic Burger", price: 4900 },
        { title: "Deep Cheese Burger", price: 4800 },
        { title: "Fillet Burger", price: 4400 },
        { title: "Chili Shrimp Burger", price: 3800 },
        { title: "Shrimp Bulgogi Burger", price: 5700 },
        { title: "Deluxe Bulgogi Burger", price: 5200 },
        { title: "Bulgogi Burger", price: 3900 },
        { title: "Shrimp Burger", price: 3500 },
        { title: "Honey&SoyThigh Boneless Chicken", price: 14500 },
        { title: "Garlic Mustard Thigh Boneless Chicken", price: 14500 },
        { title: "Hot Cheese Thigh Boneless Chicken", price: 14500 },
        { title: "Honey&Soy Chicken with Nurungji", price: 10900 },
        { title: "Garlic Mustard Chicken", price: 10900 },
        { title: "Fried Chicken", price: 9400 },
        { title: "Sweet&Spicy Korean Fried Chicken", price: 10400 },
        { title: "Fried Thigh Boneless Chicken", price: 11900 },
        { title: "Sweet&Spicy Korean Fried Thigh Boneless Chicken", price: 13900 },
        { title: "Soy Garlic Thigh Boneless Chicken", price: 13900 },
        { title: "Soy Garlic Chicken", price: 10400 },
        { title: "Cheese Sprinkled Chicken", price: 10400 },
        { title: "Sweet Corn Sprinkled Chicken", price: 10400 },
        { title: "Half and Half Chicken", price: 17900 },
        { title: "Chipao Thigh Boneless Chicken", price: 13900 },
        { title: "Cheese Springled Thigh Boneless Chicken", price: 13900 },
        { title: "Sweet Corn Sprinkled Thigh Boneless Chicken", price: 13900 },
        { title: "Fried Chicken Leg + Thigh Burger 1 + Cola 1", price: 10600 },
        { title: "Fried Chicken Leg + Thigh Burger 2 + Cola 2 + French Fries", price: 16600 },
        { title: "Fried Thigh Boneless Chicken + Thigh Burger 1 + Cola 1", price: 16600 },
        { title: "Cajun Rice Cake Gangjung", price: 4200 },
        { title: "Chipao Rice Cake Gangjung", price: 4400 },
        { title: "Soy Garlic Rice Cake Gangjung", price: 4400 },
        { title: "Chicken Gangjung Trio", price: 12000 },
        { title: "Cajun French Fries", price: 2000 },
        { title: "Cheese Sticks", price: 2000 },
        { title: "Jalapeno Nugget", price: 2000 },
        { title: "Cheese French Fries", price: 2800 },
        { title: "Kimddukman", price: 3500 },
        { title: "Popcorn Balls", price: 2600 },
        { title: "Crispy Cream Cheese Balls", price: 2000 },
      ],
    },
    {
      title: "Coffee Dutch & Bean",
      menu: [
        { title: "Americano", price: 2300 },
        { title: "Cafe Latte", price: 2800 },
        { title: "Cappuccino", price: 2800 },
        { title: "Vanilla Latte", price: 3000 },
        { title: "Caramel Macciato", price: 3300 },
        { title: "Cafe Mocha", price: 3300 },
        { title: "Ice Tea", price: 2500 },
        { title: "Real Chocolate Latte", price: 3300 },
        { title: "Sweet Potato Latte", price: 3300 },
        { title: "Green Tea Latte", price: 3300 },
        { title: "Cereal Latte", price: 3300 },
        { title: "Hot Milk", price: 2000 },
        { title: "Chrysanthemum tea", price: 3300 },
        { title: "Earl Grey Tea", price: 3000 },
        { title: "Citron Tea", price: 3000 },
        { title: "Tomato Juice", price: 3800 },
        { title: "Banana Juice", price: 3800 },
        { title: "Smoothie", price: 3500 },
        { title: "Yogurt Smoothie", price: 3800 },
        { title: "Frappe", price: 4000 },
      ],
    },
    {
      title: "Chansol Book Cafe Library",
      menu: [
        { title: "Americano Hot", price: 3300 },
        { title: "Cafe Latte", price: 3800 },
        { title: "Americano Ice", price: 3800 },
        { title: "Cafe Latte Ice", price: 4300 },
        { title: "Cappuccino Hot", price: 3800 },
        { title: "Cappuccino Ice", price: 4300 },
        { title: "Soy Latte Hot", price: 4300 },
        { title: "Soy Latte Ice", price: 4800 },
        { title: "Vanilla Latte Hot", price: 4300 },
        { title: "Vanilla Latte Ice", price: 4800 },
        { title: "Hazelnut Latte Hot", price: 4300 },
        { title: "Hazelnut Latte Ice", price: 4800 },
        { title: "Cafe Mocha Hot", price: 4300 },
        { title: "Cafe Mocha Ice", price: 4800 },
        { title: "Caramel Macciato Hot", price: 4300 },
        { title: "Caramel Macciato Ice", price: 4800 },
        { title: "Espresso", price: 3300 },
        { title: "Banana Cafe Ice", price: 4800 },
        { title: "Jeju Green Tangerine Hot", price: 4300 },
        { title: "Jeju Green Tangerine Ice", price: 4800 },
        { title: "Chamomile Hot", price: 4300 },
        { title: "Chamomile Ice", price: 4800 },
        { title: "Peppermint Hot", price: 4300 },
        { title: "Pepperming Ice", price: 4800 },
      ],
    },
  ];
  